package com.snapkeys.app.ime

/**
 * The keyboard's emoji set: category tabs for browsing and a keyword index
 * for search. Pure data + matching, so it's unit-testable.
 */
object EmojiCatalog {

    /** Tab icon → emojis, in display order. */
    val CATEGORIES: List<Pair<String, List<String>>> = listOf(
        "😀" to listOf(
            "😀", "😁", "😂", "🤣", "😊", "😇", "🙂", "😉", "😍", "🥰", "😘", "😜",
            "🤪", "🤔", "🤨", "😐", "😴", "🥱", "😎", "🥳", "😅", "😬", "🙄", "😢",
            "😭", "😤", "😡", "🤯", "😱", "🤗", "🤫", "🤤", "😷", "🤒", "🥺", "😳",
        ),
        "👍" to listOf(
            "👍", "👎", "👌", "✌️", "🤞", "🫶", "🤝", "👏", "🙌", "🙏", "💪", "👋",
            "🤙", "👉", "👈", "👆", "👇", "🖐️", "✊", "🤘",
        ),
        "❤️" to listOf(
            "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "💔", "❣️", "💕", "💯",
            "✨", "🔥", "⭐", "🌈", "✅", "❌", "❓", "❗", "💡", "🔔",
        ),
        "🎉" to listOf(
            "🎉", "🎂", "🎁", "🎵", "🎮", "⚽", "🏀", "🏆", "🎯", "🎬",
        ),
        "🐼" to listOf(
            "🌹", "🌞", "🌙", "🌍", "🌊", "🐶", "🐱", "🐼", "🦊", "🐸", "🐵", "🦁",
            "🙈", "🙉", "🙊", "🦄",
        ),
        "🍕" to listOf(
            "☕", "🍕", "🍔", "🍟", "🍦", "🍫", "🍎", "🍌", "🥑", "🍩", "🍿", "🧋",
        ),
        "🚗" to listOf(
            "🚗", "✈️", "🏠", "📱", "💻", "⌚", "📚", "💰", "🛒", "📷",
        ),
    )

    /** Substring-matched search over the keyword index, category order. */
    fun search(query: String, max: Int = 8): List<String> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return emptyList()
        return CATEGORIES.asSequence()
            .flatMap { it.second }
            .filter { KEYWORDS[it]?.contains(q) == true }
            .distinct()
            .take(max)
            .toList()
    }

    private val KEYWORDS: Map<String, String> = mapOf(
        "😀" to "grin happy smile",
        "😁" to "beam grin happy",
        "😂" to "joy laugh tears funny lol",
        "🤣" to "rofl rolling laugh funny",
        "😊" to "smile blush happy",
        "😇" to "halo angel innocent",
        "🙂" to "slight smile ok fine",
        "😉" to "wink",
        "😍" to "heart eyes love",
        "🥰" to "love hearts adore smiling",
        "😘" to "kiss love blow",
        "😜" to "wink tongue silly",
        "🤪" to "zany crazy silly goofy",
        "🤔" to "think thinking hmm",
        "🤨" to "raised eyebrow suspicious",
        "😐" to "neutral meh blank",
        "😴" to "sleep zzz tired",
        "🥱" to "yawn tired bored",
        "😎" to "cool sunglasses",
        "🥳" to "party celebrate birthday hat",
        "😅" to "sweat relief phew nervous laugh",
        "😬" to "grimace awkward cringe",
        "🙄" to "eye roll whatever",
        "😢" to "cry sad tear",
        "😭" to "sob cry loud sad bawl",
        "😤" to "huff frustrated steam triumph",
        "😡" to "angry rage mad red",
        "🤯" to "mind blown exploding head",
        "😱" to "scream fear shocked",
        "🤗" to "hug warm open hands",
        "🤫" to "shush quiet secret",
        "🤤" to "drool hungry",
        "😷" to "mask sick ill",
        "🤒" to "sick fever thermometer ill",
        "🥺" to "pleading puppy eyes cute beg",
        "😳" to "flushed embarrassed shocked",
        "👍" to "thumbs up like yes good ok",
        "👎" to "thumbs down dislike no bad",
        "👌" to "ok perfect fingers",
        "✌️" to "peace victory",
        "🤞" to "fingers crossed luck hope",
        "🫶" to "heart hands love",
        "🤝" to "handshake deal agree",
        "👏" to "clap applause bravo",
        "🙌" to "raised hands praise hooray",
        "🙏" to "pray please thanks folded",
        "💪" to "muscle strong flex gym",
        "👋" to "wave hello bye hi",
        "🤙" to "call me shaka hang loose",
        "👉" to "point right finger",
        "👈" to "point left finger",
        "👆" to "point up finger",
        "👇" to "point down finger",
        "🖐️" to "hand five stop palm",
        "✊" to "fist power bump",
        "🤘" to "rock horns metal",
        "❤️" to "red heart love",
        "🧡" to "orange heart",
        "💛" to "yellow heart",
        "💚" to "green heart",
        "💙" to "blue heart",
        "💜" to "purple heart",
        "🖤" to "black heart",
        "🤍" to "white heart",
        "💔" to "broken heart sad breakup",
        "❣️" to "heart exclamation",
        "💕" to "two hearts love",
        "💯" to "hundred percent perfect score",
        "✨" to "sparkles magic shiny new",
        "🔥" to "fire hot lit flame",
        "⭐" to "star favorite",
        "🌈" to "rainbow pride colorful",
        "✅" to "check yes done correct tick",
        "❌" to "cross no wrong delete x",
        "❓" to "question mark",
        "❗" to "exclamation important",
        "💡" to "idea bulb light",
        "🔔" to "bell notification ring",
        "🎉" to "party popper celebrate congrats confetti",
        "🎂" to "cake birthday",
        "🎁" to "gift present box",
        "🎵" to "music note song",
        "🎮" to "game controller video play",
        "⚽" to "soccer football ball",
        "🏀" to "basketball ball",
        "🏆" to "trophy win champion prize",
        "🎯" to "target dart bullseye goal",
        "🎬" to "movie clapper film",
        "🌹" to "rose flower romance",
        "🌞" to "sun sunny bright",
        "🌙" to "moon night crescent",
        "🌍" to "earth world globe planet",
        "🌊" to "wave ocean sea water",
        "🐶" to "dog puppy pet",
        "🐱" to "cat kitten pet",
        "🐼" to "panda bear",
        "🦊" to "fox",
        "🐸" to "frog",
        "🐵" to "monkey",
        "🦁" to "lion",
        "🙈" to "see no evil monkey shy hide",
        "🙉" to "hear no evil monkey",
        "🙊" to "speak no evil monkey oops",
        "🦄" to "unicorn magic",
        "☕" to "coffee tea hot drink cup",
        "🍕" to "pizza slice",
        "🍔" to "burger hamburger",
        "🍟" to "fries chips",
        "🍦" to "ice cream soft serve",
        "🍫" to "chocolate candy bar",
        "🍎" to "apple fruit red",
        "🍌" to "banana fruit",
        "🥑" to "avocado",
        "🍩" to "donut doughnut",
        "🍿" to "popcorn movie snack",
        "🧋" to "boba bubble tea milk",
        "🚗" to "car drive vehicle auto",
        "✈️" to "plane airplane flight travel",
        "🏠" to "house home",
        "📱" to "phone mobile cell",
        "💻" to "laptop computer",
        "⌚" to "watch time wrist",
        "📚" to "books study read",
        "💰" to "money bag cash rich",
        "🛒" to "cart shopping",
        "📷" to "camera photo picture",
    )
}
